DROP TABLE IF EXISTS stores;
CREATE TABLE stores (
   id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   location VARCHAR(255) NULL,
   capacity INT DEFAULT 0,
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
